-- 문제 정보
-- 생산일자가 2022-05인 식품들의 PRODUCT_ID, PRODUCT_NAME, 총매출
-- 총매출 DESC, PRODUCT_ID ASC

SELECT O.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * SUM(O.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS O
JOIN FOOD_PRODUCT AS P
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE BETWEEN "2022-05-01" AND "2022-05-31"
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,
P.PRODUCT_ID ASC

;