-- 문제 정보
-- 보호소에 들어올 때(ANIMAL_INS)는 SEX_UPON_INTAKE(Intact)
-- 나갈 때(ANIMAL_OUTS)는 Spayed or Neutered인 동물
-- ANIMAL_ID, ANIMAL_TYPE, NAME

SELECT AI.ANIMAL_ID, AI.ANIMAL_TYPE, AI.NAME
FROM ANIMAL_INS AS AI
LEFT JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%'
AND (
    AO.SEX_UPON_OUTCOME LIKE 'Spayed%'
    OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%'
)
;