-- 문제 정보
-- Front End 스킬을 가진 개발자의 정보 조회
-- ID, EMAIL, FIRST_NAME, LAST_NAME
-- ORDER BY ID ASC

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)
ORDER BY ID ASC
;