WITH COUNT_REVIEW AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE FROM REST_REVIEW AS R
LEFT JOIN MEMBER_PROFILE AS P
ON R.MEMBER_ID = P.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM COUNT_REVIEW
    WHERE CNT = (
        SELECT MAX(CNT)
        FROM COUNT_REVIEW
    )
)
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC
;