-- 문제 정보
-- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
-- MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE 출력
-- REVIEW_DATE ASC, REVIEW_TEXT ASC
WITH MAX_REVIEW_COUNT AS (
    SELECT COUNT(RR.MEMBER_ID) AS REVIEW_COUNT
    FROM REST_REVIEW AS RR
    GROUP BY RR.MEMBER_ID
    ORDER BY REVIEW_COUNT DESC
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS RR
JOIN MEMBER_PROFILE AS MP
ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(MEMBER_ID) = (
    SELECT MAX(REVIEW_COUNT)
    FROM MAX_REVIEW_COUNT)
)
ORDER BY REVIEW_DATE ASC,
RR.REVIEW_TEXT ASC
;