WITH MAX_PRICE_DATA AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT M.CATEGORY, M.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P
LEFT JOIN MAX_PRICE_DATA AS M
ON P.CATEGORY = M.CATEGORY
WHERE P.PRICE = M.MAX_PRICE
ORDER BY P.PRICE DESC
;