# SELECT * FROM ITEM_INFO AS I, ITEM_TREE AS T
# # WHERE I.ITEM_ID = T.PARENT_ITEM_ID
# # GROUP BY I.ITEM_ID, T.PARENT_ITEM_ID
# # HAVING I.ITEM_ID = T.PARENT_ITEM_ID
# # LEFT JOIN ITEM_TREE ON I.ITEM_ID = T.PARENT_ITEM_ID
# ORDER BY I.ITEM_ID DESC;

SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT T.ITEM_ID FROM ITEM_INFO AS I
    LEFT JOIN ITEM_TREE AS T ON I.ITEM_ID = T.PARENT_ITEM_ID
    WHERE RARITY = 'RARE' AND I.ITEM_ID = T.PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC;