WITH CAN_RENTAL_DATA AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.START_DATE, H.END_DATE FROM CAR_RENTAL_COMPANY_CAR AS C
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
    GROUP BY C.CAR_ID
    HAVING (H.START_DATE < '2022-11-01' AND H.END_DATE < '2022-11-01')
    OR (H.START_DATE > '2022-11-30' AND H.END_DATE > '2022-11-30')
    AND C.CAR_TYPE IN ('세단', 'SUV')
)

SELECT D.CAR_ID, D.CAR_TYPE, FLOOR(D.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE FROM CAN_RENTAL_DATA AS D
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON D.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = '30일 이상'
AND (D.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) >= 500000
AND (D.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, D.CAR_TYPE ASC, D.CAR_ID DESC
;
