-- [0] 기본 정보
-- CAR_RENTAL_COMPANY_CAR: 대여 중인 자동차들의 정보 테이블
    -- CAR_ID: 자동차 ID
    -- CAR_TYPE: 자동차 종류
    -- DAILY_FEE: 일일 대여 요금(원)
    -- OPTIONS: 옵션 리스트
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: 자동차 대여 기록 정보 테이블
    -- HISTORY_ID: 대여 기록 ID
    -- CAR_ID: 자동차 ID
    -- START_DATE: 대여 시작일
    -- END_DATE: 대여 종료일
-- CAR_RENTAL_COMPANRY_DISCOUNT_PLAN: 할인 정책 정보 테이블
    -- PLAN_ID: 할인 정책 ID
    -- CAR_TYPE: 자동차 종류
    -- DURATION_TYPE: 대여 기간 종류
    -- DISCOUNT_RATE: 할인율
    
-- 대여 기간 종류
    -- 7일 미만(할인 없음)
    -- 7일 이상(7일 이상 30일 미만)
    -- 30일 이상(30일 이상 90일 미만)
    -- 90일 이상(90일 이상)

-- [1] 문제 정보
-- 세단, SUV인 자동차 중 2022-11-1 ~ 2022-11-30까지 대여 가능
-- 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- CAR_ID, CAR_TYPE, FEE(대여 금액) 출력
-- FEE 기준으로 내림차순 정렬,
-- CAR_TYPE로 오름차순 정렬,
-- CAR_ID로 내림차순 정렬
WITH POSIBLE_TO_RENTAL AS (SELECT *
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE <= "2022-11-30"
                    AND END_DATE >= "2022-11-01")),

CORRECT_CAR_TYPE AS (SELECT *
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_TYPE = "세단"
OR CAR_TYPE = "SUV"),

FEE_IN_RANGE AS (SELECT CT.CAR_ID, (CT.DAILY_FEE * 30 / 100 * (100 - DP.DISCOUNT_RATE)) AS FIRFEE
FROM CORRECT_CAR_TYPE AS CT
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
ON CT.CAR_TYPE = DP.CAR_TYPE
WHERE DP.DURATION_TYPE = "30일 이상"
AND (CT.DAILY_FEE * 30 / 100 * (100 - DP.DISCOUNT_RATE)) >= 500000
AND (CT.DAILY_FEE * 30 / 100 * (100 - DP.DISCOUNT_RATE)) < 2000000)

SELECT DISTINCT(CCT.CAR_ID), CCT.CAR_TYPE, TRUNCATE(FIR.FIRFEE, 1) AS FEE
FROM CORRECT_CAR_TYPE AS CCT
LEFT JOIN POSIBLE_TO_RENTAL AS PTR
ON PTR.CAR_ID = CCT.CAR_ID
LEFT JOIN FEE_IN_RANGE AS FIR
ON FIR.CAR_ID = PTR.CAR_ID
WHERE FIR.FIRFEE IS NOT NULL
ORDER BY FIR.FIRFEE DESC,
CCT.CAR_TYPE ASC,
CCT.CAR_ID DESC
;