-- 문제 정보
-- 0시부터 23시까지 각 시간대별로 발생한 입양 건 수 조회
-- ORDER BY 시간대
WITH RECURSIVE TIMELINE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIMELINE
    WHERE HOUR < 23
)
SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM TIMELINE AS T
LEFT JOIN ANIMAL_OUTS AS AO
ON T.HOUR = HOUR(AO.DATETIME)
GROUP BY HOUR
ORDER BY HOUR
;