WITH RECURSIVE HOUR_DATA
AS (
    SELECT 0 AS H
    UNION ALL
    SELECT h + 1 AS H
    FROM HOUR_DATA
    WHERE h < 23
)

SELECT H.H AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM HOUR_DATA AS H
LEFT JOIN ANIMAL_OUTS AS A
ON H.H = HOUR(A.DATETIME)
GROUP BY H.H
;