-- 문제 정보
-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 비율을 년, 월 별로 출력
-- 비율 = 2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수
-- ROUND(비율, 2)
-- ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC

SELECT YEAR(SALES_DATE) AS YEAR,
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
       ROUND(COUNT(DISTINCT OS.USER_ID) / (
           SELECT COUNT(*)
           FROM USER_INFO 
           WHERE JOINED BETWEEN '2021-01-01' 
           AND '2021-12-31'
       ), 1) AS PURCHASED_RATIO
FROM USER_INFO AS UI
JOIN ONLINE_SALE AS OS
ON UI.USER_ID = OS.USER_ID
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC
;