-- 문제 정보
-- 각 세대별 자식이 없는 COUNT, GENERATION을 출력
-- ORDER BY GENERATION ASC
-- 모든 세대에는 자식이 없는 개체가 적어도 1개체 존재

WITH RECURSIVE GENER AS (
    SELECT FE.ID AS ID, 1 AS GENERATION
    FROM ECOLI_DATA AS FE
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT SE.ID, GENERATION + 1
    FROM ECOLI_DATA AS SE
    JOIN GENER AS G
    ON G.ID = SE.PARENT_ID
    
)



SELECT COUNT(*) AS COUNT, GENERATION
FROM GENER AS G
WHERE G.ID IN (
    SELECT FE.ID
    FROM ECOLI_DATA AS FE
    LEFT JOIN ECOLI_DATA AS SE
    ON FE.ID = SE.PARENT_ID
    WHERE SE.ID IS NULL
)
GROUP BY G.GENERATION
ORDER BY G.GENERATION ASC
;