WITH RECURSIVE

COUNT_DATA AS (SELECT P.ID, COUNT(C.ID) AS COUNT_ID FROM ECOLI_DATA AS P
LEFT JOIN ECOLI_DATA AS C
ON P.ID = C.PARENT_ID
GROUP BY P.ID
HAVING COUNT(C.ID) = 0),

GENERATION_DATA AS (
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, G.GENERATION + 1 AS GENERATION
    FROM GENERATION_DATA AS G
    JOIN ECOLI_DATA AS E
    ON G.ID = E.PARENT_ID
)

SELECT COUNT(G.GENERATION) AS COUNT, G.GENERATION FROM GENERATION_DATA AS G
LEFT JOIN COUNT_DATA AS C
ON G.ID = C.ID
WHERE C.COUNT_ID = 0
GROUP BY G.GENERATION
;