WITH SALES_COUNT_DATE AS (
    SELECT BOOK_ID, SUM(SALES) AS SALES_CNT
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * C.SALES_CNT) AS TOTAL_SALES
FROM BOOK AS B
LEFT JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
LEFT JOIN SALES_COUNT_DATE AS C
ON B.BOOK_ID = C.BOOK_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
;