SELECT ID,
(CASE
    WHEN COLONY_NAME = 1 THEN 'CRITICAL'
    WHEN COLONY_NAME = 2 THEN 'HIGH'
    WHEN COLONY_NAME = 3 THEN 'MEDIUM'
    WHEN COLONY_NAME = 4 THEN 'LOW'
END) AS COLONY
FROM (
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_NAME
    FROM ECOLI_DATA
) AS SUB
ORDER BY ID ASC
;