SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME FROM DEVELOPERS AS D
LEFT JOIN SKILLCODES AS S
ON (D.SKILL_CODE & S.CODE) = S.CODE
OR (D.SKILL_CODE & S.CODE) = S.CODE
WHERE S.NAME = 'Python'
OR S.NAME = 'C#'
ORDER BY ID ASC;

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME FROM DEVELOPERS
# WHERE (SKILL_CODE & 256) = 256
# OR (SKILL_CODE & 1024) = 1024
# ORDER BY ID ASC;