WITH RENTAL_DAY_DATA AS (
    SELECT H.HISTORY_ID, C.DAILY_FEE, C.CAR_TYPE, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS RENTAL_DAY,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS RENTAL_DAY_TYPE, H.START_DATE, H.END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT D.HISTORY_ID, FLOOR(DAILY_FEE * RENTAL_DAY * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM RENTAL_DAY_DATA AS D
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON D.CAR_TYPE = P.CAR_TYPE
AND D.RENTAL_DAY_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, D.HISTORY_ID DESC
;