WITH VALIDATE_CODE AS (
    SELECT 
    (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FRONT_END_CODE,
    (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') AS PYTHON_CODE,
    (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') AS CS_CODE
),

GRADE_SORTED_DATA AS (
    SELECT
    CASE
        WHEN D.SKILL_CODE & V.FRONT_END_CODE > 0 AND D.SKILL_CODE & V.PYTHON_CODE > 0 THEN 'A'
        WHEN D.SKILL_CODE & V.CS_CODE > 0 THEN 'B'
        WHEN D.SKILL_CODE & V.FRONT_END_CODE > 0 THEN 'C'
        ELSE NULL
    END AS GRADE,
    D.ID, D.EMAIL
    FROM DEVELOPERS AS D, VALIDATE_CODE AS V
)
SELECT *
FROM GRADE_SORTED_DATA
WHERE GRADE IS NOT NULL
ORDER BY GRADE ASC, ID ASC
;