WITH SECOND AS (SELECT P.PARENT_ID AS FIRST_ID, C.PARENT_ID AS SECOND_ID, C.ID AS THIRD_ID FROM ECOLI_DATA AS P
LEFT JOIN ECOLI_DATA AS C
ON P.ID = C.PARENT_ID)

SELECT S.THIRD_ID AS ID FROM ECOLI_DATA AS PP
LEFT JOIN SECOND AS S
ON PP.ID = S.FIRST_ID
WHERE PP.PARENT_ID IS NULL AND S.THIRD_ID IS NOT NULL
ORDER BY S.THIRD_ID
;