-- [0] 기본 정보
-- FIRST_HALF: 상반기 주문 정보 테이블
    -- SHIPMENT_ID(FK, JULY): 출하 번호
    -- FLAVOR(PK): 맛
    -- TOTAL_ORDER: 상반기 총 주문량
-- JULY: 7월 주문 정보 테이블
    -- SHIPMENT_ID(PK): 출하 번호
    -- FLAVOR(FK, FIRST_HALF): 맛
    -- TOTAL_ORDER: 7월 총 주문량

-- [1] 문제 정보
-- 7월 아이스크림 총 주문량 + 상반기 아이스크림 총 주문량을 큰 순서대로 상위 3개의 맛 조회

WITH JULY_TOTAL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS S
    FROM JULY
    GROUP BY FLAVOR
),
FIRST_HALF_TOTAL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS S
    FROM FIRST_HALF
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
FROM FIRST_HALF_TOTAL AS F
LEFT JOIN JULY_TOTAL AS J
ON F.FLAVOR = J.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(F.S + J.S) DESC
LIMIT 3;